

spring:
  application:
    name: CoffeeApp
  datasource:
    url: jdbc:mysql://slj.demodev.cc:3310/CoffeeAppMiahkykh?createDatabaseIfNotExist=true
    username: root
    password: "0000"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html


jwt:
  secret:
    key: zX1P4jRW7kF2yG9LhZ6V3mN8qX4aQ5bC0rT3nU7vW1yX8fL2mB5dH9eJ6sP0tA1X
  token:
    access:
      expiration: 86400000
    refresh:
      expiration: 604800000
