server:
  port: 8082
spring:


  application:
    name: CoffeeApp
  datasource:
    url: jdbc:mysql://localhost:3306/CoffeeApp5?createDatabaseIfNotExist=true
    username: root
    password: "0000"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html